### PR TITLE
Update gendata's outlier handling

### PR DESCRIPTION
**Pull request by archermarx**
This PR factors some outlier handling into a new function, splits up outliers and nans (saves to different files) and adds a flag to determine whether outliers are discarded at all.

### CODE REVIEW

**Comment by eckelsjd** [comment]
Trying this out:

1) Outliers get saved in the same pickle file for compression and test set data as a separate "outliers" key
2) Outliers are grouped by variable -- if an output QoI was considered an outlier for a given sample, then all inputs/outputs associated with that sample will be saved for that variable (will make postprocessing easier)
3) The `discard_outliers` flag will allow you to toggle whether the outliers get kept alongside the rest of the generated data
4) Samples that result in `nan` will always get discarded

**Comment by archermarx** [comment]
This looks good to me. Results are encouraging.

**Review by eckelsjd — APPROVED** [review]
This looks good for now. Might have some more changes later in order to get `fit_surr.py` working. Also, might be good to eventually move specific postprocessing code out of `gen_data.py`, such as specific plots for `u_ion` and `j_ion` -- will leave them for now.

**Comment by archermarx** [comment]
Agreed, but we'll see where they make sense to go as we proceed.

**Pull request merged**
